### ISSUE TITLE
本地部署后，侧边栏只有一项[前言]

### ISSUE THREAD

**Issue by yrucrew** [loremwalker/fq-book#7]
如题，请问是我部署的问题吗？

**Comment by loremwalker** [comment]
你都发布成功了，部署是没问题的，在 ../docs/index.html 中添加`loadSidebar: true` 配置即可；btw，你应该注意表述问题的方式
```
  <script>
    window.$docsify = {
      name: '',
      repo: '',
     <!--此处-->
      loadSidebar: true  
    }
  </script>
```

**Comment by yrucrew** [comment]
emmmmm 配置都应该是正确的
我会注意正确发问的....可是这个问题我能找到的资料不多
![image](https://user-images.githubusercontent.com/32817309/45465709-f6be6000-b748-11e8-876d-46d1cbf67f93.png)
提问可以截图吗 test 我也是第一次发问

**Comment by loremwalker** [comment]
vscode下方的浏览器显示是我的文档配置文件 index.html 的路径，这下明白了吗？
![](https://p2.cdn.img9.top/ipfs/QmauS2HsEhgsvN1RuMZc4rEJQpBmzLc7wbCzDjzGL92G7N?2.png)

**Comment by yrucrew** [comment]
我懂你说的配置侧边栏，可是我重复过所有步骤 仍然出错
![image](https://user-images.githubusercontent.com/32817309/45466600-5fa7d700-b74d-11e8-996f-dc0655fc5484.png)

**Comment by loremwalker** [comment]
这样截图 你能让我看到什么呢？图片信息较残缺还很杂乱 报错信息也没有贴出来

**Comment by yrucrew** [comment]
已经正常显示出来啦！
清理了下缓存。

打扰了....感谢回答

**Comment by machineLOVE** [comment]
没看懂，咋整啊，一模一样。

**Comment by QuentinChansey** [comment]
为什么上面那位朋友，我跟你情况一模一样，就侧边栏只显示‘前言’，index.html文件也配置正确了呀，缓存也按你说的清了一遍，怎么我的部署后还是没显示全呢？

**Comment by loremwalker** [comment]
换个浏览器试试

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________
