### ISSUE TITLE
打不开

### ISSUE THREAD

**Issue by julong491722262** [loremwalker/fq-book#8]
Administrator@xxx-HP MINGW64 /c/Users/Administrator/Desktop/fq-book-master/fq           -book-master/docs
$ docsify serve
*** DEPRECATION WARNING *** The exts option will REPLACE extensions in 0.6.4. **           *

Serving C:\Users\Administrator\Desktop\fq-book-master\fq-book-master\docs now.
Listening at http://localhost:3000

修改index.html后
打开地址后    左侧导航栏一片空白 只剩一个前言  麻烦修复一下

**Comment by loremwalker** [comment]
#7
